package application;

import javafx.fxml.FXML;

import javafx.event.ActionEvent;
import javafx.scene.control.Label;
import javafx.scene.control.TextField;
import javafx.scene.layout.StackPane;
import javafx.stage.Stage;

import java.io.IOException;

import application.rompecocos;

public class rompeController {
	
	private static final int[] NUMBERS = new int[500];
    private static final int[] NUMBERS2 = new int[500];
    private static final String[] OPERADOR = {"+","-"};
    private int numeroSeleccionado1, numeroSeleccionado2, indi, indi2, indi3, resultado1;
    String compa, op;
	
	@FXML
	private StackPane rompeContainer;
	
	@FXML
	private Label numero1, numero2, operador;
	
	@FXML
	private TextField resultado;
	
	
	  public void initialize() {
	    	numeroSeleccionado1 = seleccionarNumero1();
	    	numeroSeleccionado2 = seleccionarNumero2();
	    	op = seleccionarOperador();
	    	numero1.setText(String.valueOf(numeroSeleccionado1));
	    	numero2.setText(String.valueOf(numeroSeleccionado2));
	    	operador.setText(op);
	    	    if(op.equals("+")) {
	    	            resultado1 = indi + indi2 + 2;
	    	        }else{
	    		          resultado1= indi - indi2; 
	    	            }	
	    }
	  
	  private int seleccionarNumero1() {
		  for (int i = 0; i < 500; i++) {
		            NUMBERS[i] = i + 1; 
		        }
	        int indice = (int) (Math.random() * NUMBERS.length);
	        indi = indice;
	        return NUMBERS[indi];
	    }
	  
	  private int seleccionarNumero2() {
		  for (int i = 0; i < 500; i++) {
	            NUMBERS2[i] = i + 1; 
	        }
	        int indice = (int) (Math.random() * NUMBERS2.length);
	        indi2 = indice;
	        return NUMBERS2[indi2];
	    }
	  
	  private String seleccionarOperador() {
	        int indice = (int) (Math.random() * OPERADOR.length);
	        indi3 = indice;
	        return OPERADOR[indi3];
	    }
	
	// Event Listener on Button.onAction
	@FXML
	public void btnVerifica(ActionEvent event) throws Exception {
		// TODO Autogenerated
		String calculo = resultado.getText();
		compa = String.valueOf(resultado1);
		if(compa.equals(calculo)) {
			System.out.println("vas bien pine");
			 try {
		            Runtime.getRuntime().exec("java rompecocos");
		        } catch (IOException e) {
		            e.printStackTrace();
		        }
			
		}else {
			System.out.println("No esta ejecutando");
		}
	}
}
