package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;

import java.io.IOException;
import java.net.URL;
import java.util.ResourceBundle;

import javafx.event.Event;
import javafx.event.ActionEvent;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.layout.StackPane;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;



public class botonesController implements Initializable{
	
	
	@FXML
	private StackPane container;
	
	@FXML
    private Button btnInicio, btnRegistra;
	
	
	private VBox signInForm, signUpForm;
	
	
	

	// Event Listener on Button.onAction
	@FXML
	public void actionEvent(ActionEvent event) throws IOException{
		// TODO Autogenerated
		
		Object evt = event.getSource();
		
					
					
					
					if(evt.equals(btnInicio)) {
						   
							signInForm.setVisible(true);
							signUpForm.setVisible(false);
						
						
						
					}else if(evt.equals(btnRegistra)){
						 
						 signInForm.setVisible(false);
						 signUpForm.setVisible(true);
					}
	}
    
	@Override
	public void initialize(URL url, ResourceBundle rb) {
		// TODO Auto-generated method stub
		
			try {
				signInForm = loadForm("SignInForm.fxml");
		        signUpForm = loadForm("SignUpForm.fxml");  
				container.getChildren().addAll(signInForm, signUpForm);
				signUpForm.setVisible(false);
				signInForm.setVisible(true);
			} catch (IOException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			
		
	}
	
	 private VBox loadForm(String url) throws IOException{    
	        return (VBox) FXMLLoader.load(getClass().getResource(url));    
	    }
	
}

